# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/16_custom_buttons.ipynb (unless otherwise specified).

__all__ = []

# Internal Cell

from ipywidgets import Button

# Internal Cell

class ActionButton(Button):
    def __init__(self, value=None, **kwargs):
        super().__init__(**kwargs)
        self.value = value