# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/22_input_output_doc.ipynb (unless otherwise specified).

__all__ = []

# Internal Cell
from nbdev import show_doc
from ..mltypes import (
    InputImage,
    OutputImageLabel,
    OutputImageBbox,
    OutputVideoBbox,
    OutputGridBox,
    NoOutput
)

# Internal Cell
show_doc(InputImage, title_level=3)

# Internal Cell
show_doc(NoOutput, title_level=3)

# Internal Cell
show_doc(InputImage, title_level=3)

# Internal Cell
show_doc(OutputImageLabel, title_level=3)

# Internal Cell
show_doc(InputImage, title_level=3)

# Internal Cell
show_doc(OutputGridBox, title_level=3)

# Internal Cell
show_doc(InputImage, title_level=3)

# Internal Cell
show_doc(OutputImageBbox, title_level=3)

# Internal Cell
show_doc(InputImage, title_level=3)

# Internal Cell
show_doc(OutputVideoBbox, title_level=3)