# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00a_common_settings.ipynb (unless otherwise specified).

__all__ = ['logger', 'timestamp_format', 'im_ext']

# Cell

import logging

logging.basicConfig(
    format='%(asctime)s,%(msecs)d %(levelname)-8s [%(filename)s:%(lineno)d] '
           '%(message)s',
    datefmt='%Y-%m-%d:%H:%M:%S',
    # level=logging.DEBUG)
    level=logging.INFO)

logger = logging.getLogger("ipyannotator")
# logger.debug("This is a debug log")
# logger.info("This is an info log")
# logger.critical("This is critical")
# logger.error("An error occurred")

# Cell

timestamp_format = '%Y-%m-%d_%H-%M-%S'
im_ext = ('.jpg', '.jpeg', '.png')