# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"draw_bg": "01_bbox_canvas.ipynb",
         "draw_bounding_box": "01_bbox_canvas.ipynb",
         "get_image_size": "01_bbox_canvas.ipynb",
         "draw_img": "01_bbox_canvas.ipynb",
         "points2bbox_coords": "01_bbox_canvas.ipynb",
         "BBoxCanvas": "01_bbox_canvas.ipynb",
         "NaviGUI": "02_navi_widget.ipynb",
         "NaviLogic": "02_navi_widget.ipynb",
         "Navi": "02_navi_widget.ipynb",
         "setup_project_paths": "03_storage.ipynb",
         "get_image_list_from_folder": "03_storage.ipynb",
         "AnnotationStorage": "03_storage.ipynb",
         "AnnotationStorageIterator": "03_storage.ipynb",
         "AnnotationDBStorage": "03_storage.ipynb",
         "BBoxAnnotatorGUI": "04_bbox_annotator.ipynb",
         "BBoxAnnotatorLogic": "04_bbox_annotator.ipynb",
         "BBoxAnnotator": "04_bbox_annotator.ipynb",
         "ImageButton": "05_image_button.ipynb",
         "CaptureGrid": "06_capture_annotator.ipynb",
         "CaptureAnnotatorGUI": "06_capture_annotator.ipynb",
         "CaptureAnnotatorLogic": "06_capture_annotator.ipynb",
         "CaptureAnnotator": "06_capture_annotator.ipynb",
         "ImCanvas": "07_im2im_annotator.ipynb",
         "Im2ImAnnotatorGUI": "07_im2im_annotator.ipynb",
         "Im2ImAnnotatorLogic": "07_im2im_annotator.ipynb",
         "Im2ImAnnotator": "07_im2im_annotator.ipynb"}

modules = ["bbox_canvas.py",
           "navi_widget.py",
           "storage.py",
           "bbox_annotator.py",
           "image_button.py",
           "capture_annotator.py",
           "im2im_annotator.py"]

doc_url = "//ipyannotator"

git_url = "https://gitlab.palaimon.io/devops/ipyannotator/tree/master/"

def custom_doc_links(name): return None
