# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"draw_bg": "01_bbox_canvas.ipynb",
         "draw_bounding_box": "01_bbox_canvas.ipynb",
         "get_image_size": "01_bbox_canvas.ipynb",
         "draw_img": "01_bbox_canvas.ipynb",
         "points2bbox_coords": "01_bbox_canvas.ipynb",
         "BBoxCanvas": "01_bbox_canvas.ipynb",
         "MultiBBoxCanvas": "01_bbox_canvas.ipynb",
         "draw_bbox": "01a_datasets.ipynb",
         "xywh_to_xyxy": "01a_datasets.ipynb",
         "xyxy_to_xywh": "01a_datasets.ipynb",
         "bbox_intersection": "01a_datasets.ipynb",
         "overlap": "01a_datasets.ipynb",
         "sample_bbox": "01a_datasets.ipynb",
         "draw_rectangle": "01a_datasets.ipynb",
         "draw_ellipse": "01a_datasets.ipynb",
         "create_simple_object_detection_dataset": "01a_datasets.ipynb",
         "create_color_classification": "01a_datasets.ipynb",
         "create_shape_color_classification": "01a_datasets.ipynb",
         "create_object_detection": "01a_datasets.ipynb",
         "get_cifar10": "01a_datasets_download.ipynb",
         "get_oxford_102_flowers": "01a_datasets_download.ipynb",
         "get_cub_200_2011": "01a_datasets_download.ipynb",
         "NaviGUI": "02_navi_widget.ipynb",
         "NaviLogic": "02_navi_widget.ipynb",
         "Navi": "02_navi_widget.ipynb",
         "setup_project_paths": "03_storage.ipynb",
         "get_image_list_from_folder": "03_storage.ipynb",
         "AnnotationStorage": "03_storage.ipynb",
         "AnnotationStorageIterator": "03_storage.ipynb",
         "AnnotationDBStorage": "03_storage.ipynb",
         "BBoxAnnotatorGUI": "04_bbox_annotator.ipynb",
         "BBoxAnnotatorLogic": "04_bbox_annotator.ipynb",
         "BBoxAnnotator": "04_bbox_annotator.ipynb",
         "MultiBBoxAnnotatorGUI": "04_multi_bbox_annotator.ipynb",
         "MultiBBoxAnnotatorLogic": "04_multi_bbox_annotator.ipynb",
         "MultiBBoxAnnotator": "04_multi_bbox_annotator.ipynb",
         "ImageButton": "05_image_button.ipynb",
         "CaptureGrid": "06_capture_annotator.ipynb",
         "CaptureAnnotatorGUI": "06_capture_annotator.ipynb",
         "CaptureAnnotatorLogic": "06_capture_annotator.ipynb",
         "CaptureAnnotator": "06_capture_annotator.ipynb",
         "ImCanvas": "07_im2im_annotator.ipynb",
         "Im2ImAnnotatorGUI": "07_im2im_annotator.ipynb",
         "text_on_img": "07_im2im_annotator.ipynb",
         "flatten": "07_im2im_annotator.ipynb",
         "reconstruct_class_images": "07_im2im_annotator.ipynb",
         "Im2ImAnnotatorLogic": "07_im2im_annotator.ipynb",
         "Im2ImAnnotator": "07_im2im_annotator.ipynb"}

modules = ["bbox_canvas.py",
           "datasets/generators.py",
           "datasets/download.py",
           "navi_widget.py",
           "storage.py",
           "bbox_annotator.py",
           "image_button.py",
           "capture_annotator.py",
           "im2im_annotator.py"]

doc_url = "//ipyannotator"

git_url = "https://gitlab.palaimon.io/devops/ipyannotator/tree/master/"

def custom_doc_links(name): return None
