name: Docs2Pages
on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4.1.0
      with:
        python-version: '3.8'
    - uses: abatilo/actions-poetry@3.7.4
      with:
        poetry-version: 1.1.0
    - name: install
      run: poetry install
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        poetry run make docs
        cp -r _build/html/* ./gh-pages/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages
        folder: gh-pages